/**
 * NOTE: This class is auto generated by the swagger code generator program (2.3.1).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2018-11-19T06:18:30.042Z")

@Api(value = "login", description = "the login API")
public interface LoginApi {

    @ApiOperation(value = "Login", nickname = "login", notes = "Check if user has right access to the system", tags={ "All", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "User has access to the system"),
        @ApiResponse(code = 401, message = "Wrong user credentials") })
    @RequestMapping(value = "/login",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<Void> login(@NotNull @ApiParam(value = "Username provided for loging", required = true) @Valid @RequestParam(value = "username", required = true) String username,@NotNull @ApiParam(value = "Provided password, to be investigated how it should be hashed...", required = true) @Valid @RequestParam(value = "password", required = true) String password);

}
