/**
 * NOTE: This class is auto generated by the swagger code generator program (2.3.1).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2018-11-19T06:18:30.042Z")

@Api(value = "request_access", description = "the request_access API")
public interface RequestAccessApi {

    @ApiOperation(value = "User is able to request acceess to a room", nickname = "requestAccess", notes = "By passsing the room which user want to access a new notification  will be received by administrator ", tags={ "Employee", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Access was requested successfully"),
        @ApiResponse(code = 400, message = "Bad input"),
        @ApiResponse(code = 401, message = "Wrong user credentials"),
        @ApiResponse(code = 404, message = "Room Id was not found") })
    @RequestMapping(value = "/request_access",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<Void> requestAccess(@NotNull @ApiParam(value = "pass the room ID which is requred for unlocking", required = true) @Valid @RequestParam(value = "roomId", required = true) String roomId);

}
