pipeline {
    agent any
    stages {
        stage('---clean---') {
            steps {
                bat "mvn -f /project clean"
            }
        }
        stage('--test--') {
            steps {
                bat "mvn -f /project test"
            }
        }
        stage('--package--') {
            steps {
                bat "mvn -f /project package"
            }
        }
    }
}
