pipeline {
    agent any
    stages {
       stage('---clean---') {
                steps {
                 dir("project") {
                    bat "mvn clean -Dhttps.protocols=TLSv1.2"
                }
            }
        }
        stage('--test--') {
            steps {
                    bat "mvn test"
            }
        }
        stage('--package--') {
            steps {
                dir("project") {
                    bat "mvn package -Dhttps.protocols=TLSv1.2"
                }
            }
        }
    }
}
