pipeline {
    agent any
    stages {
        stage('---clean---') {
            steps {
                dir("project") {
                    sh "mvn clean -Dhttp.protocols=TLSv1.2"
                }
            }
        }
        stage('--test--') {
            steps {
                dir("project") {
                    sh "mvn test"
                }
            }
        }
        stage('--package--') {
            steps {
                dir("project") {
                    sh "mvn package -Dhttps.protocols=TLSv1.2"
                    echo 'I will always say Hello again'
                    sh "ssh nanii_tolea@35.239.211.109 rm -rf /var/www/temp_deploy/dist/"
                    echo 'I will always say Hello again'
                }
            }
        }
    }
 }
