/**
 * NOTE: This class is auto generated by the swagger code generator program (2.3.1).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2018-11-19T06:18:30.042Z")

@Api(value = "give_access", description = "the give_access API")
public interface GiveAccessApi {

    @ApiOperation(value = "give access", nickname = "giceAccess", notes = "Give access to a employee to a room", tags={ "Administrator", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "User has access to the room"),
        @ApiResponse(code = 400, message = "Bad input"),
        @ApiResponse(code = 401, message = "Wrong user credentials"),
        @ApiResponse(code = 403, message = "User do not have access to perform this") })
    @RequestMapping(value = "/give_access",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<Void> giceAccess(@NotNull @ApiParam(value = "Username provided for access", required = true) @Valid @RequestParam(value = "username", required = true) String username,@NotNull @ApiParam(value = "Room to which employee will have acceess", required = true) @Valid @RequestParam(value = "roomId", required = true) String roomId);

}
